"""add session verification state

Revision ID: 42959f6f49a8
Revises: 783071e4f0d9
Create Date: 2026-08-21 16:24:57.373951

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42959f6f49a8'
down_revision: str | Sequence[str] | None = '783071e4f0d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_sessions', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('call_sessions', sa.Column('verified_patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'call_sessions', 'patients', ['verified_patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_sessions', type_='foreignkey')
    op.drop_column('call_sessions', 'verified_patient_id')
    op.drop_column('call_sessions', 'verified')
    # ### end Alembic commands ###
