"""create initial healthcare tables

Revision ID: 783071e4f0d9
Revises: 5580130dc2bf
Create Date: 2026-08-17 18:36:16.702062

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '783071e4f0d9'
down_revision: str | Sequence[str] | None = '5580130dc2bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
